# Output directory for writing results
output_dir: ./outputs

# Bowtie2 index
idx_bt2: ./hg38/bowtie2_index/hg38

# Path to a TSV file with samples and their corresponding FASTQ file paths.
SAMPLES_TSV: './sample.tsv'

# Path to chromosome sizes file
chrom_sizes: "./genome_inf/hg38.22XY.chrom.sizes"

# Path to blacklisted regions file
blacklist: "./genome_inf/hg38_maxatac_blacklist_merged.bed"

# Slop size to use around the Tn5 insertion sites
slop: 20

# What is the millions factor that you want to use to scale the read counts
million_factor: 20000000

# MACS2 species
species: "hs"

# List of chromosomes to limit the study to
keepChr: 'chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY'